spring:
  data:
    redis:
      host: localhost
      port: 6379
      redisson:
        wait-time: 2000
        lease-time: 2000

logging:
  level:
    root: INFO

fcfs:
  event:
    name: CHICKEN
    limit: 1000
  queue:
    admit:
      request: 50
      delay: 500
